version: '2'
services:
  web:
    restart: always
    build: .
    command: bash -c "cd /angular-first/angular_first/ && npm start"
    volumes:
      - .:/angular-first
      - /angular-first/angular_first/node_modules
    ports:
      - "3000:3000"
